#!/bin/sh /etc/rc.common

START=95
STOP=10

#USE_PROCD=1 # line possibly not needed since this is a one time exec during boot process

start() {
    logger "MODEBOOT: Starting mode detection"

    # remove system handling GPIO
    rmmod gpio_button_hotplug

    # Export GPIOs
    for p in 18 20; do
        [ ! -d /sys/class/gpio/gpio$p ] && echo $p > /sys/class/gpio/export
    done

    sleep 1

    V18=$(cat /sys/class/gpio/gpio18/value)
    V20=$(cat /sys/class/gpio/gpio20/value)

    # Clean up
    for p in 18 20; do
        echo $p > /sys/class/gpio/unexport
    done

    # return GPIOhandle to system
    insmod /lib/modules/*/gpio-button-hotplug.ko

    case "$V18$V20" in
        "10")
            logger "MODEBOOT: MODE1 (USB WAN)"
            /root/mode_manager.sh MODE1
            ;;
        "01")
            logger "MODEBOOT: MODE2 (RJ45 WAN)"
            /root/mode_manager.sh MODE2
            ;;
        "11")
            logger "MODEBOOT: MODE3 (External WiFi)"
            /root/mode_manager.sh MODE3
            ;;
        *)
            logger "MODEBOOT: Unknown switch state $V18$V20"
            ;;
    esac

    logger "MODEBOOT: Switch detection $V18$V20"

    # prep Guest and Emergency WiFi off                                                  
    uci set wireless.inner_guest.disabled='1'                                                  
    uci set wireless.emergency.disabled='1'                                
    uci commit wireless 
    wifi reload
    logger "MODEBOOT: Guest+Emergency Wifi disabled"

    # Restart network cleanly
    /etc/init.d/network restart

    logger "MODEBOOT: Network Restarted. Modeboot Exiting..."

    touch /tmp/daemon_LED_Ctrl
    /root/led_daemon.sh &  #start the LED daemon
    logger "MODEBOOT: LED_Ctrl created + daemon started"
}


